### PR TITLE
add revamp favicon and update manifest.json accordingly

### PR DESCRIPTION
**Pull request by ksdfg**

### CODE REVIEW

**Review by AniketRaj314 — APPROVED** [review]
LGTM

**Review by akhilnarang — COMMENTED** [review]
`%PUBLIC_URL%` is needed? It should work with just /favicon?
Besides that, seems ok

**Comment by ksdfg** [comment]
> `%PUBLIC_URL%` is needed? It should work with just /favicon?
> Besides that, seems ok

Well, they that's how the favicon was set pehle bhi....

**Comment by akhilnarang** [comment]
Yeah saw, seems ehh tho, lemme try without locally once

**Review by akhilnarang — APPROVED** [review]

**Pull request merged**
