### PR TITLE
AMP-36 React Cookie

### PR DESCRIPTION
**Pull request by AniketRaj314**
Dependencies added:
- react-cookie

The get() and set() work in Login. Will need to test in other components
once they are built

For now, have made access_token to path: '/' (throughout the React App)

### CODE REVIEW

**Comment by ksdfg** [comment]
how do I test this?

**Comment by akhilnarang** [comment]
image
First before login, second after.
Seems good!

**Review by akhilnarang — DISMISSED** [review]

**Comment by ksdfg** [comment]
image

@aniket-spidey not sure if firefox specific

cookie being set correctly tho

**Comment by ksdfg** [comment]
@ksdfg check this

**Comment by AniketRaj314** [comment]
Cool, will read react-cookie ka doc and see how does it handle this, and push the changes.

**Comment by PranavBakre** [comment]
just set same site so that your cookie isnt shared among other domains. add in options argument for set()

**Review by ksdfg — APPROVED** [review]

**Review by adityavdesai — APPROVED** [review]

**Pull request merged**
