### PR TITLE
AMP-51: Terms Page

### PR DESCRIPTION
**Pull request by ksdfg**

### CODE REVIEW

**Comment by akhilnarang** [comment]
image
Can we disable negative here?

**Comment by akhilnarang** [comment]
Electives toggle seems to require a double click, else doesn't switch

**Comment by PranavBakre** [comment]
@akhilnarang ! I havent seen the code yet but is the initial value null?

**Comment by ksdfg** [comment]
@akhilnarang This I honestly don't know, cuz it's the same as the other toggle switches

**Review by PranavBakre — APPROVED** [review]
More or less looks good. Some fixes in bugfix for switch issue

**Review by PranavBakre — DISMISSED** [review]

**Review by PranavBakre — APPROVED** [review]

**Review by adityavdesai — APPROVED** [review]

**Pull request merged**
