### PR TITLE
AMP-47: Users

### PR DESCRIPTION
**Pull request by PranavBakre**
The /users page for listing users

### CODE REVIEW

**Review by akhilnarang — COMMENTED** [review]
Looks mostly fine. Just needs some formatting, as well as 1 small change, can you display `profile_picture` as a column - if the string isn't empty, it'll contain the picture, base64 encoded.

**Comment by ksdfg** [comment]
@psbakre #everyone review plejj

**Review by ksdfg — DISMISSED** [review]

**Comment by PranavBakre** [comment]
@ksdfg It is my pr

**Review by ksdfg — DISMISSED** [review]

**Review by ksdfg — DISMISSED** [review]

**Review by ksdfg — DISMISSED** [review]

**Comment by ksdfg** [comment]
@psbakre #everyone review karlo and merge

**Review by akhilnarang — APPROVED** [review]

**Review by akhilnarang — CHANGES_REQUESTED** [review]
There's still a few small things that need to be worked on, mentioned on Telegram.

**Review by akhilnarang — APPROVED** [review]
Seems fine for now!

**Review by ksdfg — APPROVED** [review]

**Pull request merged**
